### ISSUE TITLE
Investigations_Mise à jour des fiches

### ISSUE THREAD

**Issue by thibaud-cl** [incubateur-territoires/incubateur-directus#1]
ETQ que coach

JE SOUHAITE que les fiches des investigations dont j'ai la charge soient mise à jour (en front) sur le site quand je passe leur statut de "en préparation" à "en cours". 

POUR rendre publiques les informations renseignées. 

EN L'ETAT, malgré le changement de statut des fiches site affiche toujours l'investigation en "en préparation", sans contenu. 

**URL Directus** : https://directus.incubateur.anct.gouv.fr/admin/collections/investigations/85  (Se connecter par ex avec le compte de Renaud Pons ID renaud.pons@beta.gouv.fr MDP : Incubateur2021

![image](https://user-images.githubusercontent.com/77704762/119670703-67463600-be39-11eb-9adc-967ece075711.png)

**URL site** : https://incubateur.anct.gouv.fr/investigation/85

![image](https://user-images.githubusercontent.com/77704762/119670639-57c6ed00-be39-11eb-8fbc-717eaad02b1e.png)

@vinyll @pichot 

#high

**Comment by pichot** [comment]
Le site se mets à jour à minuit tous les jours automatiquement. Ça veut dire que la mise à jour se fait pas immediatement, mais la jour d'après. C'est pas parfait comme fonctionnement, mais pour l'instant ça dévrait le faire.
