### ISSUE TITLE
Investigations_Billets de blog écrasés

### ISSUE THREAD

**Issue by thibaud-cl** [incubateur-territoires/incubateur-directus#10]
ETQ : Coach 
 
JE SOUHAITE : pouvoir publier plusieurs posts de blogs à la suite sur une même investigation. 
 
POUR : documenter correctement le tout le processus au fur et à mesure et donner à voir l'avancée du projet à tous les utilisateurs finaux
 
EN L'ETAT : la publication de billets de blog fonctionne et apparaît dans le back office Directus. Toutefois, le texte de chacun des billets apparaît comme similaire : le texte du dernier billet rédigé écrase automatiquement celui du billet précédent dans la prévisualisation. 

Par ailleurs, un autre bug est lié : dans l'exemple ci-dessous, la mise en forme du deuxième texte n'est pas conservé alors qu'elle apparaît bien sur le premier texte. 
 
URL Directus : https://directus.incubateur.anct.gouv.fr/admin/collections/investigations/73
 
URL site : https://incubateur.anct.gouv.fr/investigation/73

Depuis Directus, partie blog : 

![image](https://user-images.githubusercontent.com/77704762/121369606-4bb05480-c93c-11eb-8fdb-a3706f6f257c.png)

Billet 1 avec le texte (mise en forme) du billet 2 : 

![image](https://user-images.githubusercontent.com/77704762/121369718-6256ab80-c93c-11eb-99c9-a192d806fcd3.png)

Billet 2 avec le bon texte mais non mis en forme

![image](https://user-images.githubusercontent.com/77704762/121369770-6f739a80-c93c-11eb-8230-935698510e91.png)

**Comment by vinyll** [comment]
Après échanges, le souci pourrait provenir :
- soit d'un malentendu d'ergonomie
- soit d'une utilisation de Directus de plusieurs utilisateurs sur les mêmes articles qui s'écrasent les uns les autres.

En attente de tests utilisateurs complémentaires…
