### ISSUE TITLE
Reset password non continnel

### ISSUE THREAD

**Issue by b-vand** [incubateur-territoires/incubateur-directus#11]
1. Le lien de réinitialisation de mot de passe est bien envoyé

2. Par une fois sur la page de réinitialisation du mot de passe, lorsque je clique sur "Reset" le message d'erreur "Invalid Payload" s'affiche.

**Comment by pand-app** [comment]
Il faut mettre à jour Directus, cf https://github.com/directus/directus/issues/6927
Je m'en occupe

**Comment by pand-app** [comment]
@b-vand C'est à jour, je te laisse tester et si c'est OK fermer le ticket.
