### ISSUE TITLE
Investigations_Edition des fiches coachs et modification de mot de passe

### ISSUE THREAD

**Issue by thibaud-cl** [incubateur-territoires/incubateur-directus#3]
**ETQ** coach
 
**JE SOUHAITE** éditer ma propre fiche en renseignant mes informations (Prénom, nom, mail, avatar) et changer le mot de passe par défaut fixé par les administrateurs ("Incubateur 2021")
 
**POUR** m'approprier l'outil, compléter les informations présentes et alimenter la base de données avec mes informations de contact (utile pour la partie "Equipe" rendue publique)
 
**EN L'ETAT** l'intégralité de ma fiche est grisée et je ne peux rien modifier 
 
**URL Directus** :https://directus.incubateur.anct.gouv.fr/admin/users/c3906e08-68a3-4116-9fe8-26dcb4aad898 (Connexion test avec renaud.pons@beta.gouv.fr et MDP : Incubateur2021)

**Comment by pichot** [comment]
C'est fait.

**Comment by thibaud-cl** [comment]
Merci ! Un dernier point : quelles sont les règles de création de mot de passe ? En testant Incubateur2021, j'ai le message suivant "la valeur n'a pas le bon format". 

En revanche ça marche avec Incubateur2021@ ;)
