### ISSUE TITLE
Investigations_Préciser les coordonnées des membres de l'équipe

### ISSUE THREAD

**Issue by thibaud-cl** [incubateur-territoires/incubateur-directus#5]
**ETQ** coach
 
**JE SOUHAITE** par l'intermédiaire de l'item "équipe", ajouter mes coordonnées de contact (mail), voire celles des agents si volontaires 
 
**POUR** favoriser la prise de contact de parties prenantes extérieures et potentiellement nourrir ma propre investigation (autres coachs beta, collectivités extérieures intéressées)
 
**EN L'ETAT** seuls les noms, prénoms et fonctions peuvent être renseignées 

NB : en l'état, il ne m'est pas encore possible d'ajouter des membres à mon équipe (cf issue #3 )
 
**URL Directus** : https://directus.incubateur.anct.gouv.fr/admin/collections/investigations/85
 
![image](https://user-images.githubusercontent.com/77704762/119697074-1ee64280-be50-11eb-996c-511675020a3c.png)

**Comment by b-vand** [comment]
Cela semble OK si on parle bien de de la partie "Members", parce que je n'ai pas trouvé la section "Équipe".
